version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: jopersr/backend:latest
    container_name: backend
    environment:
      MONGODB_URI: "mongodb://root:password@mongo:27017/dbname?authSource=admin"
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    image: jopersr/frontend:latest
    container_name: frontend
    environment:
      VITE_BACKEND_URL: "http://localhost:3000"
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo-data:
